import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import Barcode from 'react-barcode';

import { api } from "@/utils/api";
import {CalendarDays, MapPin} from "lucide-react";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Voyager - Home</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen bg-gray-900 font-body">
          <header className="flex items-center justify-between max-w-4xl w-full  mx-auto text-gray-100 text-sm h-[80px]">
              <div className="space-x-4 flex ">
                  <h4 className="font-bold text-orange-500">VG</h4>
                  <nav className="flex gap-x-2.5">
                        <Link href="/home">Accueil</Link>
                        <Link href="/cart">Panier</Link>
                        <Link href="/order">Mes commandes</Link>
                  </nav>
              </div>

              <div className="space-x-2.5">
                  <Link href="/register">S'enegistrer</Link>
                  <Link href="/login">Connexion</Link>
              </div>
          </header>

          <section className="max-w-4xl w-full mx-auto grid grid-cols-2 mt-12 ">
              <div>
                  <div>
                      <p className="text-5xl font-semibold font-title text-gray-100">Your world is</p>
                      <p className="text-5xl font-semibold font-title text-gray-100">worth sharing</p>
                  </div>

                  <form action="" className="mt-8 space-y-2.5">
                      <div>
                          <label className="text-gray-100 text-sm">Départ</label>
                          <div className="bg-gray-50 flex rounded-sm divide-x-2 divide-dashed divide-gray-800 p-1.5">
                              <input className="w-full appearance-none outline-none focus:outline-none px-2.5 py-2 text-sm text-gray-700" />
                              <span className="w-16  flex items-center justify-center">
                                  <MapPin className="w-4 h-4 stroke-gray-800" />
                              </span>
                          </div>
                      </div>
                        <div className="mt-4">
                          <label className="text-gray-100 text-sm">Arrivée</label>
                          <div className="bg-gray-50 flex rounded-sm divide-x-2 divide-dashed divide-gray-800 p-1.5">
                              <input className="w-full appearance-none outline-none focus:outline-none px-2.5 py-2 text-sm text-gray-700" />
                              <span className="w-16  flex items-center justify-center">
                                  <MapPin className="w-4 h-4 stroke-gray-800" />
                              </span>
                          </div>
                        </div>

                      <div className="mt-4">
                          <label className="text-gray-100 text-sm">Date</label>
                          <div className="bg-gray-50 flex rounded-sm divide-x-2 divide-dashed divide-gray-800 p-1.5">
                              <input type="date" className="w-full appearance-none outline-none focus:outline-none px-2.5 py-2 text-sm text-gray-700" />
                              <span className="w-16  flex items-center justify-center">
                                  <CalendarDays className="w-4 h-4 stroke-gray-800" />
                              </span>
                          </div>
                      </div>

                      <div className=" flex items-center space-x-3.5 text-gray-100 text-sm">
                          <label htmlFor="" className=" flex items-center uppercase space-x-1">
                              <input type="radio" className="w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 " />
                              <span>Direct</span>
                          </label>

                          <label htmlFor="" className=" flex items-center uppercase space-x-1">
                              <input type="radio" className="w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 " />
                              <span>Escale</span>
                          </label>
                      </div>

                      <div className="pt-4">
                        <button className="bg-orange-600 text-orange-100  px-10 py-4 rounded-full text-xs font-semibold">BOOK NOW</button>
                      </div>
                  </form>
              </div>
              <div className="flex items-center justify-end ">

                  <div className="w-72 font-semibold p-4 rounded-xl bg-gray-50 text-gray-700">
                      <div className="flex items-center justify-between">
                        <span className="py-1 px-2 font-medium rounded-sm bg-orange-600 text-orange-100 text-xs">Economy </span>
                        <span className="text-xs">UK - BD</span>
                      </div>

                      <div className="mt-4">
                          <h4>6 Flight Tickets</h4>

                          <div className="grid grid-cols-2 font-medium mt-3 ">
                            <div className=" flex-grow">
                                <p className="text-[8px] text-gray-600">Passager</p>
                                <p className="text-[11px] text-gray-800">Math Done</p>
                            </div>
                              <div className=" flex-grow">
                                  <p className="text-[8px] text-gray-600">Date</p>
                                  <p className="text-[11px] text-gray-800">24 Juin 2023</p>
                              </div>
                          </div>

                          <div className="grid grid-cols-2 font-medium mt-3 ">
                              <div className=" flex-grow">
                                  <p className="text-[8px] text-gray-600">Vol</p>
                                  <p className="text-[11px] text-gray-800">202972878</p>
                              </div>
                              <div className=" flex-grow">
                                  <p className="text-[8px] text-gray-600">Portail</p>
                                  <p className="text-[11px] text-gray-800">A</p>
                              </div>
                          </div>

                          <div className="grid grid-cols-2 font-medium mt-3 ">
                              <div className="flex-grow">
                                  <p className="text-[8px] text-gray-600">Type de vol</p>
                                  <p className="text-[11px] text-gray-800">Direct</p>
                              </div>
                              <div className=" flex-grow">
                                  <p className="text-[8px] text-gray-600">Siège</p>
                                  <p className="text-[11px] text-gray-800">12 - 15</p>
                              </div>
                          </div>
                      </div>

                      <div className=" relative border-t-4 border-gray-800 border-dashed mt-4">
                          <span className="absolute w-6 h-6 bg-gray-900 rounded-full -left-4 -translate-x-1/2 -translate-y-1/2 "></span>
                          <span className="absolute w-6 h-6 bg-gray-900 rounded-full -right-10 -translate-x-1/2 -translate-y-1/2 "></span>
                      </div>

                      <div className="  flex  ">
                          <Barcode   displayValue={false} value="barcode-example" />
                      </div>
                  </div>

              </div>
          </section>
      </main>
    </>
  );
};

export default Home;
