import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { api } from "@/utils/api";
import { Key, Mail } from "lucide-react";
import {ChangeEvent, FormEventHandler, useState} from "react";
import {useRouter} from "next/router";

const Home: NextPage = () => {
    const [email, setEmail] = useState<string>('');
    const [password, setPassword] = useState<string>('');
    const register = api.auth.register.useMutation().mutate;

    function onEmailChange(e: ChangeEvent<HTMLInputElement>) {
        setEmail(e.target.value);
    }

    function onPasswordChange(e: ChangeEvent<HTMLInputElement>) {
        setPassword(e.target.value);
    }

    function onSubmit(e) {
        e.preventDefault();
        console.log({ email, password });
    }

    return (
        <>
            <Head>
                <title>Voyager - Login</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="min-h-screen bg-gray-900 font-body">
                <header className="flex items-center justify-between max-w-4xl w-full  mx-auto text-gray-100 text-sm h-[80px]">
                    <div className="space-x-4 flex ">
                        <h4 className="font-bold text-orange-500">VG</h4>
                        <nav className="flex gap-x-2.5">
                            <Link href="/home">Accueil</Link>
                            <Link href="/cart">Panier</Link>
                            <Link href="/order">Mes commandes</Link>
                        </nav>
                    </div>

                    <div className="space-x-2.5">
                        <Link href="/register">S'enegistrer</Link>
                        <Link href="/login">Connexion</Link>
                    </div>
                </header>

                <section className="max-w-md w-full mx-auto mt-20">
                    <div>
                        <h4 className="text-lg font-semibold text-gray-100">Login </h4>
                        <form onSubmit={onSubmit} className="mt-8 space-y-2.5">
                            <div>
                                <label className="text-gray-100 text-sm">Email</label>
                                <div className="bg-gray-50 flex rounded-sm divide-x-2 divide-dashed divide-gray-800 p-1.5">
                                    <input onChange={onEmailChange} type="email" className="w-full appearance-none outline-none focus:outline-none px-2.5 py-2 text-sm text-gray-700" />
                                    <span className="w-16  flex items-center justify-center">
                                        <Mail className="w-4 h-4 stroke-gray-800" />
                                    </span>
                                </div>
                            </div>
                            <div className="mt-4">
                                <label className="text-gray-100 text-sm">Mot de passe</label>
                                <div className="bg-gray-50 flex rounded-sm divide-x-2 divide-dashed divide-gray-800 p-1.5">
                                    <input onChange={onPasswordChange} type="password" className="w-full appearance-none outline-none focus:outline-none px-2.5 py-2 text-sm text-gray-700" />
                                    <span className="w-16  flex items-center justify-center">
                                        <Key className="w-4 h-4 stroke-gray-800" />
                                    </span>
                                </div>
                            </div>

                            <div className="pt-4">
                                <button className="bg-orange-600 text-orange-100  px-10 py-4 rounded-full text-xs font-semibold">Se connecter</button>
                            </div>
                        </form>
                    </div>

                </section>
            </main>
        </>
    );
};

export default Home;
