import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { PropsWithChildren } from "react";


type MainLayoutProps = PropsWithChildren<{ title: string }>;

 function MainLayout({ title, children }: MainLayoutProps) {

    return (
        <>
            <Head>
                <title>Voyager - {title}</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="min-h-screen bg-gray-900 font-body">
                <header className="flex items-center justify-between max-w-4xl w-full  mx-auto text-gray-100 text-sm h-[80px]">
                    <div className="space-x-4 flex ">
                        <h4 className="font-bold text-orange-500">VG</h4>
                        <nav className="flex gap-x-2.5">
                            <Link href="/">Accueil</Link>
                            <Link href="/cart">Panier</Link>
                            <Link href="/order">Mes commandes</Link>
                        </nav>
                    </div>

                    <div className="space-x-2.5">
                        <Link href="/register">S&lsquo;enegistrer</Link>
                        <Link href="/login">Connexion</Link>
                    </div>
                </header>
                {children}
            </main>
        </>
    );
}

export default MainLayout;
